### ISSUE TITLE
utteranc.es 설치 문제

### ISSUE THREAD

**Issue by InhyeokYoo** [rubato-yeong/rubato-yeong.github.io#1]
안녕하세요.

현재 github pages에 utterance가 설치되지 않은거 같습니다.

> Error: utterances is not installed on rubato-yeong/comments. If you own this repo, [install the app](https://github.com/apps/utterances). Read more about this change in [the PR](https://github.com/utterance/utterances/pull/25).

확인해보시길 바랍니다.

본 이슈와 별개로 블로그 내 유익한 내용 많이 읽고갑니다.
감사합니다.

**Comment by rubato-yeong** [comment]
utterances 문제 수정하였습니다.

좋게 읽어주셔서 감사합니다 😄
